attribute_means:
  elev_mean: 282.755
  slope_mean: 23.20534
attribute_stds:
  elev_mean: 176.40843224366193
  slope_mean: 14.13095216367248
xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.4437105655670166
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 5.77202844619751
    rand_col:
      dims: []
      attrs: {}
      data: 0.28582626581192017
    tmax(C):
      dims: []
      attrs: {}
      data: 10.48847484588623
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 0.9705083966255188
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 2.7667407989501953
    rand_col:
      dims: []
      attrs: {}
      data: 0.4848152697086334
    tmax(C):
      dims: []
      attrs: {}
      data: 15.147065162658691
