batch_size: 256
checkpoint_path:
create_new_files: true
dataset: CAMELS
debug: true
dropout_rate: 0.4
learning_rate: 1e-05
limit_size_above_1000: false
load_checkpoint: false
model: Transformer_Encoder
num_basins:
num_epochs: 10
num_hidden_units: 256
num_processes_ddp: 3
num_workers_data_loader: 2
optim: Adam
print_tqdm_to_console: true
profile_code: false
run_sweeps: true
save_checkpoint: true
sequence_length: 270
sequence_length_spatial: 14
use_all_static_attr: false