{batch_size: 128, checkpoint_path: null, create_new_files: false, dataset: CAMELS,
  debug: true, dropout_rate: 0.4, intermediate_dim_transformer: 32, learning_rate: 5e-05,
  limit_size_above_1000: true, load_checkpoint: false, model: Transformer_Encoder,
  num_basins: null, num_epochs: 10, num_heads_transformer: 8, num_hidden_units: 256,
  num_layers_transformer: 6, num_processes_ddp: 3, num_workers_data_loader: 2, optim: Adam,
  print_tqdm_to_console: true, profile_code: false, run_sweeps: false, save_checkpoint: true,
  sequence_length: 270, sequence_length_spatial: 14, test_end_date: 30/09/1997, test_start_date: 01/10/1992,
  train_end_date: 30/09/2007, train_start_date: 01/10/1997, use_all_static_attr: false,
  validation_end_date: 30/09/1992, validation_start_date: 01/10/1988}
