batch_size: 256
checkpoint_path:
create_new_files: true
dataset: CAMELS
debug: false
dropout_rate: 0.4
learning_rate: 5e-04
limit_size_above_1000: true
load_checkpoint: false
model: CNN_LSTM
mode: validation
num_basins:
num_epochs: 15
num_hidden_units: 256
num_processes_ddp: 3
num_workers_data_loader: 2
optim: Adam
print_tqdm_to_console: true
profile_code: false
run_sweeps: false
save_checkpoint: true
sequence_length: 1
sequence_length_spatial: 450
use_all_static_attr: false
train_start_date: '01/10/1999'
train_end_date: '30/09/2008'
validation_start_date: "01/10/1988"
validation_end_date: "30/09/1993"
test_start_date: "01/10/1993"
test_end_date: "30/09/1999"
intermediate_dim_transformer: 512
num_heads_transformer: 6
num_layers_transformer: 8
num_runs: 1
use_random_noise_in_spatial_data: true
use_zeros_in_spatial_data: false
only_precip: false
run_with_radar_data: false