batch_size: 512
checkpoint_path:
create_new_files: false
dataset: CAMELS
debug: false
dropout_rate: 0.4
learning_rate: 5e-04
limit_size_above_1000: true
load_checkpoint: false
model: LSTM
mode: validation
num_basins:
num_epochs: 15
num_hidden_units: 256
num_processes_ddp: 3
num_workers_data_loader: 2
optim: Adam
print_tqdm_to_console: true
profile_code: false
run_sweeps: false
save_checkpoint: true
sequence_length: 270
sequence_length_spatial: 14
use_all_static_attr: false
train_start_date: "01/10/1997"
train_end_date: "30/09/2002"
validation_start_date: "01/10/1988"
validation_end_date: "30/09/1992"
test_start_date: "01/10/1992"
test_end_date: "30/09/1997"
intermediate_dim_transformer: 512
num_heads_transformer: 6
num_layers_transformer: 8
num_runs: 1
only_precip: true
run_with_radar_data: false