model:
  "LSTM"
dataset:
  "CARAVAN"
optim:
  "Adam"
num_epochs:
  10
sequence_length_spatial:
  14
num_processes_ddp:
  3
num_workers_data_loader:
  2
batch_size:
  256
save_checkpoint:
  true
debug:
  true
print_tqdm_to_console:
  true
load_checkpoint:
  false
limit_size_above_1000:
  true
learning_rate:
  1e-5
sequence_length:
  270
num_hidden_units:
  256
dropout_rate:
  0.4
create_new_files:
  false
checkpoint_path:
  ""