xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.7412116527557373
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 5.823116779327393
    tmax(C):
      dims: []
      attrs: {}
      data: 10.468042373657227
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    QObs(mm/d):
      dims: []
      attrs: {}
      data: 1.346714973449707
    prcp(mm/day):
      dims: []
      attrs: {}
      data: 2.767058849334717
    tmax(C):
      dims: []
      attrs: {}
      data: 12.536142349243164
